### PR TITLE
[6.0.x] URL.deletingLastPathComponent() should append .. in special cases

### PR DESCRIPTION
**Pull request by jrflat**
**Explanation:** Corrects `URL.deletingLastPathComponent()` behavior to append `..` in special cases, such as when the relative path is empty or ends in a `..` segment. This makes `.deletingLastPathComponent()` semantically accurate when resolving against a base URL.
**Scope:** Only impacts `URL.deletingLastPathComponent()` in special cases of relative paths.
**Original PR:** #989  
**Risk:** Low - Small change to fix behavior for these edge cases.
**Testing:** Added comprehensive unit test, swift-ci, stable in `main`
**Reviewer:** @itingliu 

Resolves https://github.com/swiftlang/swift-foundation/issues/922 for `release/6.0`

### CODE REVIEW

**Comment by jrflat** [comment]
@swift-ci please test

**Comment by jrflat** [comment]
Oh, the test expects the behavior from the `String.deletingLastPathComponent()` fixes in #1013, which is not yet in `release/6.0`.

**Comment by jrflat** [comment]
@swift-ci please test

**Comment by jrflat** [comment]
Tests pass now that #1013 is merged

**Review by parkera — APPROVED** [review]

**Pull request merged**
