### PR TITLE
[Proposal] SF-0010 Amend proposal to make types Hashable

### PR DESCRIPTION
**Pull request by hristost**
Update the proposal to also make some of the recently introduced types Hashable.

### CODE REVIEW

**Review by parkera — APPROVED** [review]
Makes sense to me!

**Review by itingliu — APPROVED** [review]

**Comment by itingliu** [comment]
@swift-ci please test

**Comment by hristost** [comment]
Force-pushed to indicate `Calendar.RecurrenceRule.Weekday` should also be Hashable

**Comment by hristost** [comment]
@swift-ci please test

**Comment by hristost** [comment]
@swift-ci please test

**Pull request merged**
