### PR TITLE
Ensure that FileManager.copyItem cannot copy directory metadata to files

### PR DESCRIPTION
**Pull request by jmschonfeld**
`FileManager.copyItem(atPath:toPath:)` has a TOCTOU bug due to how it recursively copies directories. As we recursively copy directories, we copy the directory itself with default metadata/permissions, copy the contents of the directory, then copy the metadata over (which may change permissions on the directory, including potentially making it read-only). This TOCTOU bug allows another process with write access to the source directory to (with the right timing) cause a process that uses `FileManager.copyItem` to copy and apply metadata to a file rather than a directory.

To fix the TOCTOU issue, the post-order traversal which copies the metadata now:

- Opens a file descriptor to both the source and destination directories
- `fstats` the source and destination directories to validate that they are directories (and not files)
- Then copies metadata from one open file descriptor to the other
    - This uses `fcopyfile` on Darwin, and a custom function on Linux where `fcopyfile` does not exist

This ensures that we only copy metadata between directories and cannot accidentally apply metadata to a file.

### CODE REVIEW

**Comment by jmschonfeld** [comment]
@swift-ci please test

**Review by parkera — APPROVED** [review]

**Comment by jmschonfeld** [comment]
@swift-ci please test

**Comment by jmschonfeld** [comment]
@swift-ci please test

**Comment by jmschonfeld** [comment]
@swift-ci please test Linux platform

**Comment by jmschonfeld** [comment]
@swift-ci please test macOS Platform

**Pull request merged**
